build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,14 +1,16 @@
 #! /bin/bash
 
-if [ "$SUDO_USER" == "" ]; then
-  echo "This script must be run with sudo command from a non-root user"
+if [ "$SUDO_USER" != "" ]; then
+  echo "ERROR	: This script will call sudo as required and must be run by non-root user"
+  echo "TRY	:   . ./build"
+  echo "NOTE	:   ^extra period is significant"
   exit -1
 fi
 
 if [ -e CMakeFiles ] ; then 
   echo removing existing makefiles
-  rm -rf CMakeCache.txt CMakeFiles CMakeFiles.txt target cmake_install.cmake CPackConfig.cmake CPackSourceConfig.cmake
-  sudo -u $SUDO_USER mkdir target
+  sudo rm -rf CMakeCache.txt CMakeFiles CMakeFiles.txt target cmake_install.cmake CPackConfig.cmake CPackSourceConfig.cmake
+  mkdir target
 fi
 
 if [ "$(arch)" != "armv6l" ] || [ "$(lsb_release -is)" != "Debian" ] ;then
@@ -25,7 +27,7 @@ function help() {
   echo "Build FireFUSE for Raspbian"
   echo 
   echo "EXAMPLES:"
-  echo "  sudo ./build"
+  echo "  ../build"
   echo
   echo "OPTIONS:"
   echo "  -h"
@@ -51,116 +53,122 @@ done
  
 
 if [ "$(type -p cmake)" == "" ]; then
-  echo "++++++++++++++++++ INSTALLING CMAKE ++++++++++++"
+  echo "INSTALL	: cmake ..."
   if [ `uname -o` == "Solaris" ]; then
-    pkgin -y install gmake
-    pkgin -y install cmake
+    sudo pkgin -y install gmake
+    if [ $? -ne 0 ]; then echo "ERROR	: Installation failed"; exit -1; fi
+    sudo pkgin -y install cmake
+    if [ $? -ne 0 ]; then echo "ERROR	: Installation failed"; exit -1; fi
   else
-    apt-get -y install cmake
+    sudo apt-get -y install cmake
+    if [ $? -ne 0 ]; then echo "ERROR	: Installation failed"; exit -1; fi
   fi
-else
-  echo CMAKE OK
 fi
+echo "STATUS	: cmake installed"
 
 if [ "$(type -p lsb_release)" == "" ]; then
-  echo "++++++++++++++++++ INSTALLING lsb_release ++++++++++++"
-  apt-get install -y lsb_release
+  ccho "INSTALL	: lsb_release ..."
+  sudo apt-get install -y lsb_release
 fi
+echo "STATUS	: lsb_release installed"
 
 if [ ! -e /usr/local/include/jansson.h ] ; then
-  echo "++++++++++++++++++ INSTALLING JANNSON C LIBRARY ++++++++++++"
-  apt-get -y install dh-autoreconf
+  echo "INSTALL	: jansson ..."
+  sudo apt-get -y install dh-autoreconf
   git clone git://github.com/akheron/jansson jannson
   pushd jannson
   autoreconf -i
   ./configure
   cmake .
-  make install
+  if [ $? -ne 0 ]; then echo "ERROR	: Installation failed"; exit -1; fi
+  sudo make install
+  if [ $? -ne 0 ]; then echo "ERROR	: Installation failed"; exit -1; fi
   popd
 fi
+echo "STATUS	: jansson installed"
 
 if [ "$cv" == "make" ] ;then
-  echo "++++++++++++++++++ BUILDING OPENCV C++ LIBRARIES ++++++++++++"
-  echo "apt-get: Installing openexr for libIlmImf.so.6"
-  apt-get -y install openexr
-  apt-get -y install libavcodec-dev
-  apt-get -y install libavformat-dev
-  apt-get -y install libswscale-dev
-  apt-get -y install libdc1394-22
-  apt-get -y install libz-dev
+  echo "STATUS	: building OPENCV C++ libraries (this will take hours)"
+  echo "INSTALL	: openexr for libIlmImf.so.6"
+  sudo apt-get -y install openexr
+  sudo apt-get -y install libavcodec-dev
+  sudo apt-get -y install libavformat-dev
+  sudo apt-get -y install libswscale-dev
+  sudo apt-get -y install libdc1394-22
+  sudo apt-get -y install libz-dev
 
   if [ ! -e opencv ] ; then
-    sudo -u $SUDO_USER git clone https://github.com/firepick1/opencv -b 2.4
+    git clone https://github.com/firepick1/opencv -b 2.4
   fi
-  sudo -u $SUDO_USER mkdir opencv/build
+  mkdir opencv/build
   pushd opencv/build
-    sudo -u $SUDO_USER cmake \
+    cmake \
       -D WITH_OPENEXR=OFF \
       -D CMAKE_BUILD_TYPE=DEBUG \
       -D CMAKE_INSTALL_PREFIX=/usr/local \
       ..
-    sudo -u $SUDO_USER make 
-    make install
+    make 
+    sudo make install
   popd
 elif [ -e /usr/lib/libopencv_core.so ]; then
-  echo "OpenCV found in /usr/lib:"
+  echo "STATUS	: OpenCV found in /usr/lib:"
   ls /usr/lib/libopencv_core.so.*
 elif [ -e /usr/local/lib/libopencv_core.so ]; then
-  echo "OpenCV found in /usr/local/lib:"
+  echo "STATUS	: OpenCV found in /usr/local/lib:"
   ls /usr/local/lib/libopencv_core.so.*
 else
-  echo "++++++++++++++++++ INSTALLING OPENCV C++ LIBRARIES ++++++++++++"
-  apt-get install -y libopencv-dev
+  echo "INSTALL	: OPENCV C++ libraries"
+  sudo apt-get install -y libopencv-dev
 fi
 
 if [ ! -e /usr/include/fuse.h ] ; then
-  echo "++++++++++++++++++ INSTALLING FUSE C LIBRARIES ++++++++++++"
-  apt-get -y install libfuse-dev
-  ex -s -c "g/#user_allow_other/s/#//" -c wq /etc/fuse.conf
+  echo "INSTALL	: FUSE C Libraries ..."
+  sudo apt-get -y install libfuse-dev
+  sudo ex -s -c "g/#user_allow_other/s/#//" -c wq /etc/fuse.conf
   echo "/usr/local/lib" > /etc/ld.so.conf.d/firefuse.conf
-  ldconfig
+  sudo ldconfig
 fi
 if [ ! -e /usr/lib/libfirepicam.so ]; then
-  echo "++++++++++++++++++ INSTALLING firepicam C++ LIBRARY ++++++++++++"
+  echo "INSTALL	: libfirepicam ..."
   pushd ..
-  sudo -u $SUDO_USER git clone git://github.com/firepick1/FirePiCam
+  git clone git://github.com/firepick1/FirePiCam
   popd
   pushd ../FirePiCam
-  ./build
+  sudo -E ./build
   popd
 fi
 if [ ! -e /usr/lib/lib_firesight.so ]; then
-  echo "++++++++++++++++++ INSTALLING firesight C++ LIBRARY ++++++++++++"
+  echo "INSTALL	: FireSight ..."
   pushd ..
-  sudo -u $SUDO_USER git clone git://github.com/firepick1/FireSight
+  git clone git://github.com/firepick1/FireSight
   popd
   pushd ../FireSight
-  ./build
+  . ./build
   popd
 fi
 if [ ! -e /opt/node ] ;then
-  echo installing Nodejs...
-  mkdir /opt/node
+  echo "INSTALL	: nodejs ..."
+  sudo mkdir /opt/node
   pushd /opt/node
-  wget http://nodejs.org/dist/v0.10.22/node-v0.10.22-linux-arm-pi.tar.gz
-  tar xvzf node-*-linux-arm-pi.tar.gz
-  rm node-v0.10.22-linux-arm-pi.tar.gz
-  mv node*/* .
-  ex -s -c 'g/PATH/s/"$/:\/opt\/node\/bin"/' -c wq /etc/profile
+  sudo wget http://nodejs.org/dist/v0.10.22/node-v0.10.22-linux-arm-pi.tar.gz
+  sudo tar xvzf node-*-linux-arm-pi.tar.gz
+  sudo rm node-v0.10.22-linux-arm-pi.tar.gz
+  sudo mv node*/* .
+  sudo ex -s -c 'g/PATH/s/"$/:\/opt\/node\/bin"/' -c wq /etc/profile
   source /etc/profile
   popd
 fi
 
 # Agressively dismount /dev/firefuse
-echo Uninstalling /dev/firefuse...
-fusermount -uq /dev/firefuse 
+echo "STATUS	: unmounting /dev/firefuse..."
+sudo fusermount -uq /dev/firefuse 
 if [ $? -ne 0 ]; then 
-  echo "non-zero result (VERIFYING): fusermount -uq /dev/firefuse"
+  echo "WARNING	: non-zero result (VERIFYING): fusermount -uq /dev/firefuse"
   if [ -e /dev/firefuse ]; then
-    rmdir /dev/firefuse
+    sudo rmdir /dev/firefuse
     if [ $? -ne 0 ]; then
-      echo "FAILED: fusermount -uq /dev/firefuse"
-      echo "If you are running NodeJS FireREST web server, kill it"
+      echo "FAILED	: fusermount -uq /dev/firefuse"
+      echo "TRY	: If you are running NodeJS FireREST web server, kill it"
       ps -ef | grep firerest.js | grep -v -e "grep firerest"
       exit -1
     fi
@@ -168,46 +176,47 @@ if [ $? -ne 0 ]; then
 fi
 
 if [ ! -e /dev/firefuse ]; then 
-  echo mkdir /dev/firefuse 
-  mkdir /dev/firefuse 
+  echo "STATUS	: mkdir /dev/firefuse "
+  sudo mkdir /dev/firefuse 
 fi
 
-echo creating makefiles
-sudo -u $SUDO_USER cmake .
+echo "STATUS	: creating makefiles"
+cmake .
 
-echo building and installing FireFUSE...
-sudo -u $SUDO_USER make
+echo "STATUS	: building and installing FireFUSE..."
+make
 if [ $? -ne 0 ]; then
-  echo FAILED: make
+  echo "FAILED	: make"
+  echo "TRY	: correct make errors and retry"
   exit -1
 fi
 
-echo installing FireFUSE...
-make install
+sudo make install
 if [ $? -ne 0 ]; then
-  echo FAILED: make install
+  echo "FAILED	: FireFUSE installation failed"
   exit -1
 fi
+echo "STATUS	: FireFUSE installed"
 
 if [ -e /var/firefuse/cv ]; then
-  rm -rf /var/firefuse/cv
-  rm -rf /var/firefuse/sync/cv
+  sudo rm -rf /var/firefuse/cv
+  sudo rm -rf /var/firefuse/sync/cv
 fi
 echo initializing /var/firefuse
 if [ -e /var/firefuse/config.json ]; then
-  mv -f /var/firefuse/config.json /var/firefuse/config.json.bak
-  echo Saved old /var/firefuse/config.json as /var/firefuse/config.json.bak
+  sudo mv -f /var/firefuse/config.json /var/firefuse/config.json.bak
+  echo "INFO	: Saved old /var/firefuse/config.json as /var/firefuse/config.json.bak"
 fi
-cp var/firefuse/config.json /var/firefuse/
+sudo cp var/firefuse/config.json /var/firefuse/
 
-echo Mounting the multi-threaded firefuse file system on /dev/firefuse
-echo   target/firefuse -o allow_other /dev/firefuse
-target/firefuse -o allow_other /dev/firefuse
+echo "STATUS	: Mounting the multi-threaded firefuse file system on /dev/firefuse"
+echo "COMMAND	: target/firefuse -o allow_other /dev/firefuse"
+sudo target/firefuse -o allow_other /dev/firefuse
 if [ $? -ne 0 ]; then
   echo "!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!"
-  echo "COULD NOT MOUNT /dev/firefuse"
-  echo  FireFUSE has not been installed
-  echo  Dumping /var/log/firefuse.log:
+  echo "ERROR	: COULD NOT MOUNT /dev/firefuse"
+  echo "ERROR	: FireFUSE has not been installed"
+  echo "ERROR	: Dumping /var/log/firefuse.log:"
   echo
   cat /var/log/firefuse.log
   echo "!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!"
@@ -216,18 +225,18 @@ fi
 
 if [ -e /dev/firefuse/status ]; then
   if [ ! -e /etc/rc5.d/S01mountfirefuse.sh ]; then
-    ./postinst
+    sudo ./postinst
   fi
-  echo "FireFUSE installed at startup in /dev/firefuse"
+  echo "STATUS	: FireFUSE installed at startup in /dev/firefuse"
 else
   echo "!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!"
-  echo "FireFUSE mount failed: /dev/firefuse/status is missing"
-  echo  Dumping /var/log/firefuse.log
-  echo  FireFUSE has not been installed
+  echo "ERROR	: FireFUSE mount failed: /dev/firefuse/status is missing"
+  echo "ERROR	: Dumping /var/log/firefuse.log"
+  echo "ERROR	: FireFUSE has not been installed"
   cat /var/log/firefuse.log
   echo "!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!"
   exit -1
 fi
 
-grep FireFUSE version.h
-echo "FireFUSE installation is complete!"
+echo "VERSION	: "`grep FireFUSE version.h`
+echo "SUCCESS	: FireFUSE installation is complete!"
