raspistill

diff --git a/build b/build
--- a/build
+++ b/build
@@ -191,6 +191,11 @@ fi
 #  popd > /dev/null
 #fi
 
+echo "COMMAND	: sudo cp raspistill.sh /usr/local/bin/raspistill.sh"
+sudo cp raspistill.sh /usr/local/bin/raspistill.sh
+RC=$?
+if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+
 ps -ef | grep raspistill | grep -v grep | grep -v 'raspistill.sh' 
 RC=$?
 if [ $RC -eq 0 ]; then 
@@ -256,11 +261,6 @@ if [ $? -ne 0 ]; then
   echo "!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!"
   exit -1
 fi
-
-echo "COMMAND	: sudo cp raspistill.sh /usr/local/bin/raspistill.sh"
-sudo cp raspistill.sh /usr/local/bin/raspistill.sh
-RC=$?
-if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
 
 if [ -e /dev/firefuse/status ]; then
   if [ ! -e /etc/rc5.d/S01mountfirefuse.sh ]; then
